[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Redirect all routes to index.html (for React Router)
# Proxy all /api/* calls to Render
[[redirects]]
  from = "/api/*"
  to = "https://laser-sharks-auth.onrender.com/api/:splat"
  status = 200
  force = true
