[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Redirect all routes to index.html (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
